# 公共配置文件
spring:
  application:
    name: chat-stomp-gateway
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 127.0.0.1
  port: 9005
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - dev.runtian.helpcommunity.controller
dubbo:
  application:
    name: chat-stomp-gateway
  protocol:
    name: dubbo
    port: 9111
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
